name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install pnpm
      run: npm install --global pnpm
    - name: Install dependencies
      run: cd test && pnpm install
    - name: Install Playwright Browsers
      run: cd test && pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: cd test && pnpm exec playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: test/playwright-report/
        retention-days: 30
